### PR TITLE
Expose `ScnLoadData.RequestId()`

### LINKED ISSUE #280: No access to requestId needed in call to DataReadyAsync()
I'm currently working on a project where sciter (i.e. a loaded script) needs to request resources (and other data) from a DBMS. So, I'm trying to implement a callback handler to respond to the `SC_LOAD_DATA` notifications of such requests. My intention is to return `LOAD_DELAY` immediately, query the database from a separate goroutine, and then call `sciter.DataReadyAsync()`, with the returned data, from that same goroutine. However, `sciter.DataReadyAsync()` takes the `requestId` as its third parameter, but the go-sciter API doesn't appear to give access to that value; and if I pass `nil` as the `requestId`, the entire DOM is reloaded with the returned data. Below is the basic design of my handler code:
```go
func SampleHandler(s *sciter.Sciter) func(*sciter.ScnLoadData) int {
	return func(params *sciter.ScnLoadData) int {
		// capture the values while they are valid
		uri := params.Uri()
		//requestID := params.RequestID() // this accessor does not exist in the current API

		go func() {
			// NOTE: 'params' is no longer valid
			time.Sleep(time.Millisecond * 500) // simulated network lag
			buf := []byte("sample data")       // data returned from the DBMS
			s.DataReadyAsync(uri, buf, nil)
		}()

		return sciter.LOAD_DELAYED
	}
}
```
Now, as mentioned, when the above code is called to handle a request, the entire DOM is reloaded to display the text: "sample data". I've tried implementing the accessor function that is out-commented in the code above, as shown below:
```go
// this was placed in types.go
func (s *ScnLoadData) RequestID() uintptr {
	return uintptr(s.requestId)
}
```
However, if I use the accessor function to get the `requestId`, and call `sciter.DataReadyAsync()` as follows:
```go
s.DataReadyAsync(uri, buf, unsafe.Pointer(requestID))
```
the request simply times out.

---
Below is the TIScript code making the request:
```
function self.ready() {
	self.timer(500ms, ()=>{
		var data = self.request(1500, #get, "db:test")
		stdout.println(data.toString("utf-8"))
	})
}
```

EDIT: Also, in the first block of code, there's a comment that highlights the fact that `params` is no longer valid at that point. What this means, is that calling `params.Uri()` at that point **sometimes** return erroneous data, and causes a segfault. So, I feel like a big part of why this isn't working is because the underlying C++ object is being destroyed, and Go just ends up holding an invalid reference.

### PR DESCRIPTION
**Pull request by pravic**
Fixes #280.

### CODE REVIEW

File: sciter.go [hunk 1]
```diff
@@ -134,17 +134,17 @@ var (
...
 	if len(data) > 0 {
 		pData = (C.LPCBYTE)(unsafe.Pointer(&data[0]))
 	}
 	curi := StringToWcharPtr(uri)
 	cdataLength := C.UINT(len(data))
-	crequestId := C.LPVOID(requestId)
+
 	// cgo call
-	ret := C.SciterDataReadyAsync(s.hwnd, curi, pData, cdataLength, crequestId)
+	ret := C.SciterDataReadyAsync(s.hwnd, curi, pData, cdataLength, requestId)
```
Comment (AshfordN) [inline sciter.go:147]: This would cause Go to throw the following compile error:
`cannot use _cgo4 (type _Ctype_HREQUEST) as type _Ctype_LPVOID in argument to _Cfunc_SciterDataReadyAsync`

So perhaps you still need that `C.LPVOID` conversion?

File: types.go [hunk 2]
```diff
@@ -1008,6 +1008,10 @@ func (s *ScnLoadData) Uri() string {
 	return Utf16ToString((*uint16)(unsafe.Pointer(s.uri)))
 }
 
+func (s *ScnLoadData) RequestId() C.HREQUEST {
+	return s.RequestId
```
Comment (AshfordN) [inline types.go:1012]: This is returning the function itself. Instead, this should be:
```go
return s.requestId
```

**Review by AshfordN — CHANGES_REQUESTED** [review]

File: types.go (hunk 2 above)
Comment (pravic) [reply types.go:1012]: Right, I was confused by the wrong comment:
https://github.com/sciter-sdk/go-sciter/blob/97143d145ba550c4c2d5ccf49ceb8ff7a1962f79/types.go#L996-L1005

File: types.go [hunk 3]
```diff
@@ -1008,8 +1008,8 @@ func (s *ScnLoadData) Uri() string {
 	return Utf16ToString((*uint16)(unsafe.Pointer(s.uri)))
 }
 
-func (s *ScnLoadData) RequestId() C.HREQUEST {
-	return s.RequestId
+func (s *ScnLoadData) RequestId() C.LPVOID {
+	return s.requestId
```
Comment (AshfordN) [inline types.go:1012]: This still has some type conversion issues here. I'm not sure which type you're more comfortable returning from this function, but currently the `requestId` is of type `C.HREQUEST`; so, if you're going to return `C.LPVOID` then you'd have to convert the value before returning it. Either that, or you go back to the previous version that returned the `C.HREQUEST` value and keep the following line, from the original the `DataReadyAsync()` function:
```
crequestId := C.LPVOID(requestId)
```
This is actually what I was suggesting in my original comment.

Comment (pravic) [reply types.go:1012]: https://github.com/sciter-sdk/go-sciter/blob/3b6704eea9f9da3e1730a584a4c694ce6d7844df/include/sciter-x-def.h#L182

https://github.com/sciter-sdk/go-sciter/blob/3b6704eea9f9da3e1730a584a4c694ce6d7844df/include/sciter-x-request.h#L29

Isn't this the same as `C.LPVOID`?

Comment (AshfordN) [reply types.go:1012]: Looks the same to me, but Go complains about it for some reason.

**Comment by AshfordN** [comment]
This is fine now.
